---
title: "HW2_Group #1_Austin Halvorsen"
author: "Pedram Jahangiry"
date: "Sep 15 2020"
output:
  word_document: 
    keep_md: yes
  pdf_document: default
---



\newpage

# Problems

## Question 1

### (i) 

```{r echo=FALSE, comment=NA}
v1 <- seq(1,17,4)

v1
```

### (ii)

## Question 2

### (i)

```{r echo=FALSE, comment = NA}
my_data <- 20:39
header_names <- LETTERS[1:5]
A <- matrix(my_data, nrow = 4, ncol = 5, byrow = TRUE) 
A
colnames(A) <- header_names
A
```

### (ii)

```{r echo=FALSE, comment=NA}
# Extracting Columns B & D

B <- A[c(2,4),c("B","D")]
```

### (iii)

```{r echo=FALSE, comment=NA}
# Transpose Matrix B

t(B)
```

### (iv)

```{r echo=FALSE, comment=NA}
# Inverse of Matrix B

B_inverse <- solve(B)
B_inverse
```

### (v)

```{r echo=FALSE, comment=NA}
B %*% B_inverse
```

## Question 3

### (i)

```{r echo=FALSE, comment=NA}
df <- data.frame(mtcars)
head(df,10)
```

### (ii)

```{r echo=FALSE, comment=NA}
library(dplyr)
df1 <- df %>% 
  select(c(cyl, hp, wt, vs, am, gear, mpg)) %>% 
  arrange(cyl) %>% 
  head(5)
```

### (iii)

```{r echo=FALSE, comment=NA}
df1 %>% 
  mutate(gpm = round((1/df1$mpg),3)) %>% 
  head(5)
```

### (iv)

```{r echo=FALSE, comment=NA}
str(df1)
```

### (v)

```{r echo=FALSE, comment=NA}
names <- c('vs', 'am', 'cyl', 'gear')
df1[,names] <- lapply(df1[,names] , factor)
str(df1)
```

---------



# Computer Exercises

```{r include=FALSE, comment=NA}
library(wooldridge)
df2 <- wooldridge::alcohol
df2 <- df2 %>% 
  select(abuse, status) 
```

## Alcohol Dataset for Questions

### (i) 
```{r include=FALSE, comment=NA}
prop.table(table(df2$abuse))
```


### (ii)
```{r include=FALSE, comment=NA}

```


### (iii)

### (iv)

### (v)
 







# Including r output within some text 

for example I calculated the average number of cars as: 
```{r}
avg_speed <- mean(cars$speed)
avg_speed
```

from the R output above, we see that the average speed is equal to 15.4. 

Or you could directly do some in-line calculations. 
Here is the average speed: `r mean(cars$speed)`. 

We can also insert plots from R in Rmarkdown: 


```{r}
hist(wage2$wage, col="red")
```



-------------


How to write mathematical formulas in **Rmarkdown**: 

1. Writing in-line formulas using one dollar sign: $y=\beta_0 + \beta_1 x_1 + ... + \beta_k x_k + u$


2. Writing centered and stand alone formulas using 2 dollar signs: 
$$y=\beta_0 + \beta_1 x_1 + ... + \beta_k x_k + u$$
$$P(X|Y)$$

$log(salary)$

$P(X \le 6)$

$f(x)=3x^2 -2x^3$  then $0 \le x \le 1$

---------------




